"""
Standardized logging utilities for LLM providers.
Provides consistent logging patterns across all providers.
"""

from core.logging_config import get_logger
from i18n import _


class ProviderLogger:
    """Standardized logger for LLM providers."""
    
    def __init__(self, provider_name: str):
        self.provider_name = provider_name
        self.logger = get_logger(f"llm.{provider_name.lower()}_provider")
    
    def log_configuration_start(self):
        """Log configuration start."""
        self.logger.debug(_("Configuring {} provider").format(self.provider_name))
    
    def log_configuration_success(self, details: str = ""):
        """Log successful configuration."""
        if details:
            self.logger.info(_("{} provider configured: {}").format(self.provider_name, details))
        else:
            self.logger.info(_("{} provider configured successfully").format(self.provider_name))
    
    def log_configuration_error(self, error: Exception):
        """Log configuration error."""
        self.logger.error(_("Error configuring {} provider: {}").format(self.provider_name, error))
    
    def log_initialization_start(self):
        """Log initialization start."""
        self.logger.info(_("Initializing {} provider").format(self.provider_name))
    
    def log_initialization_success(self, details: str = ""):
        """Log successful initialization."""
        if details:
            self.logger.info(_("{} provider initialized: {}").format(self.provider_name, details))
        else:
            self.logger.info(_("{} provider initialized successfully").format(self.provider_name))
    
    def log_initialization_error(self, error: Exception):
        """Log initialization error."""
        self.logger.error(_("Failed to initialize {} provider: {}").format(self.provider_name, error))
    
    def log_connection_test_start(self, endpoint: str = ""):
        """Log connection test start."""
        if endpoint:
            self.logger.debug(_("Testing {} connection to {}").format(self.provider_name, endpoint))
        else:
            self.logger.debug(_("Testing {} connection").format(self.provider_name))
    
    def log_connection_success(self):
        """Log successful connection."""
        self.logger.info(_("{} server connection successful").format(self.provider_name))
    
    def log_connection_error(self, error: Exception):
        """Log connection error."""
        self.logger.error(_("Failed to connect to {} server: {}").format(self.provider_name, error))
    
    def log_generation_start(self, prompt_length: int, model: str = "", params: dict = None):
        """Log text generation start."""
        self.logger.info(_("=== {} REQUEST ===").format(self.provider_name.upper()))
        if model:
            self.logger.info(_("Model: {}").format(model))
        self.logger.info(_("Prompt length: {} characters").format(prompt_length))
        if params:
            param_str = ", ".join([f"{k}={v}" for k, v in params.items()])
            self.logger.info(_("Parameters: {}").format(param_str))
    
    def log_generation_success(self, response_length: int, stats: dict = None):
        """Log successful text generation."""
        self.logger.info(_("=== {} RESPONSE ===").format(self.provider_name.upper()))
        self.logger.info(_("Response length: {} characters").format(response_length))
        if stats:
            for key, value in stats.items():
                self.logger.info(f"{key}: {value}")
    
    def log_generation_error(self, error: Exception):
        """Log generation error."""
        self.logger.error(_("Error in {} generation: {}").format(self.provider_name, error))
    
    def log_request_timeout(self):
        """Log request timeout."""
        self.logger.error(_("Request to {} server timed out").format(self.provider_name))
    
    def log_server_error(self, status_code: int, message: str = ""):
        """Log server error."""
        if message:
            self.logger.error(_("{} server error {}: {}").format(self.provider_name, status_code, message))
        else:
            self.logger.error(_("{} server returned status {}").format(self.provider_name, status_code))
    
    def log_no_response(self):
        """Log no response error."""
        self.logger.error(_("No text generated by {} server").format(self.provider_name))
    
    def log_provider_not_initialized(self):
        """Log provider not initialized error."""
        self.logger.error(_("{} provider not initialized").format(self.provider_name))
    
    def log_cleanup(self):
        """Log cleanup completion."""
        self.logger.debug(_("{} provider cleaned up").format(self.provider_name))
    
    def log_file_operation_error(self, operation: str, error: Exception):
        """Log file operation error."""
        self.logger.warning(_("Failed to {} file: {}").format(operation, error))